'use client'

import { useState, useEffect } from 'react'
import { CAC_STYLES, fmt, fmtRoas } from '@/lib/utils'
import { findByFbAdId, findByAdName, type LibraryEntry } from '@/lib/creativeLibrary'
import type { CacRating } from '@/lib/accounts'

export interface CreativeDay {
  spend: number; purchases: number; cac: number; roas: number; revenue: number
  clicks: number; impressions: number; frequency: number; ctr: number
}

export interface CreativeData {
  id: string
  name: string
  platform: 'facebook' | 'tiktok' | 'google_ads'
  accountName: string
  currency: string
  cacRating: CacRating
  days: Record<string, CreativeDay>
  primaryCac: number
  primarySpend: number
  totalPurchases: number
  thumbnailUrl?: string
}

interface CreativeCardProps {
  creative: CreativeData
  days: string[]
}

const PLATFORM_BADGE: Record<string, string> = {
  facebook:   'bg-blue-50 text-blue-700',
  tiktok:     'bg-purple-50 text-purple-700',
  google_ads: 'bg-green-50 text-green-700',
}
const PLATFORM_LABEL: Record<string, string> = {
  facebook: 'Facebook', tiktok: 'TikTok', google_ads: 'Google',
}
const PLATFORM_PLACEHOLDER_BG: Record<string, string> = {
  facebook: 'bg-blue-50', tiktok: 'bg-purple-50', google_ads: 'bg-green-50',
}
const PLATFORM_PLACEHOLDER_TEXT: Record<string, string> = {
  facebook: 'text-blue-200', tiktok: 'text-purple-200', google_ads: 'text-green-200',
}

// Parse launch date from ad name pattern "| DD/M/YYYY" or "| DD/M/YY" at end of name
function parseCreativeAge(name: string): number | null {
  const match = name.match(/\b(\d{1,2})\/(\d{1,2})\/(\d{2,4})\s*$/)
  if (!match) return null
  const [, d, m, y] = match
  const year = y.length === 2 ? 2000 + parseInt(y) : parseInt(y)
  const launch = new Date(year, parseInt(m) - 1, parseInt(d))
  const now = new Date(); now.setHours(0, 0, 0, 0)
  const days = Math.floor((now.getTime() - launch.getTime()) / 86400000)
  return days >= 0 ? days : null
}

export default function CreativeCard({ creative, days }: CreativeCardProps) {
  const [activeDay, setActiveDay] = useState(0)
  const [aiEntry, setAiEntry]     = useState<LibraryEntry | null>(null)
  const [showDna, setShowDna]     = useState(false)

  useEffect(() => {
    const entry = findByFbAdId(creative.id) ?? findByAdName(creative.name)
    setAiEntry(entry)
  }, [creative.id, creative.name])
  const dayKey  = days[activeDay]
  const prevKey = days[activeDay + 1]
  const d    = creative.days[dayKey]  ?? { spend: 0, purchases: 0, cac: 0, roas: 0, revenue: 0, clicks: 0, impressions: 0, frequency: 0, ctr: 0 }
  const prev = prevKey ? (creative.days[prevKey] ?? null) : null

  const style = CAC_STYLES[creative.cacRating]

  // CAC trend vs previous day (negative = improving = green)
  const cacTrendPct = (d.cac > 0 && prev && prev.cac > 0)
    ? ((d.cac - prev.cac) / prev.cac) * 100
    : null

  // Fatigue: only meaningful for Facebook (where we have real CTR + frequency data)
  const hasCtrData = creative.platform === 'facebook' && d.impressions > 500
  const isFatiguing = hasCtrData && d.ctr < 1.0 && d.frequency > 1.5

  const age = parseCreativeAge(creative.name)

  return (
    <div className="card overflow-hidden flex flex-col">
      {/* Thumbnail */}
      <div className="h-24 relative overflow-hidden">
        {creative.thumbnailUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={creative.thumbnailUrl} alt="" className="w-full h-full object-cover" />
        ) : (
          <div className={`w-full h-full flex items-center justify-center ${PLATFORM_PLACEHOLDER_BG[creative.platform]}`}>
            <span className={`text-4xl font-bold tracking-tighter select-none ${PLATFORM_PLACEHOLDER_TEXT[creative.platform]}`}>
              {PLATFORM_LABEL[creative.platform].charAt(0)}
            </span>
          </div>
        )}
        <span className={`badge ${PLATFORM_BADGE[creative.platform]} absolute top-2 left-2 text-xs`}>
          {PLATFORM_LABEL[creative.platform]}
        </span>
        {age !== null && (
          <span className="badge bg-black/50 text-white absolute top-2 right-2 text-xs">
            D-{age}
          </span>
        )}
        {aiEntry && (
          <button
            onClick={() => setShowDna(p => !p)}
            className="absolute bottom-2 left-2 badge bg-violet-600 text-white text-[10px] hover:bg-violet-700 transition-colors"
            title="Generated by Creative Studio"
          >
            🤖 AI Studio
          </button>
        )}
      </div>
      {aiEntry && showDna && (
        <div className="bg-violet-50 border-b border-violet-100 px-3 py-2 space-y-0.5">
          <p className="text-[10px] font-bold text-violet-700 uppercase">AI Creative Brief</p>
          <p className="text-[11px] text-violet-800 leading-snug">{aiEntry.dna}</p>
          <p className="text-[10px] text-violet-500">Headline: "{aiEntry.headline}" · {aiEntry.concept} · {aiEntry.audienceStage}</p>
          <p className="text-[10px] text-violet-400">{aiEntry.genId}</p>
        </div>
      )}

      {/* CAC rating stripe */}
      <div className={`h-1 w-full ${style.stripe}`} />

      {/* Body */}
      <div className="p-3 flex flex-col gap-2 flex-1">
        <div className="text-xs font-medium text-gray-900 leading-tight line-clamp-2" title={creative.name}>
          {creative.name}
        </div>
        <div className="text-xs text-gray-400">{creative.accountName}</div>

        {/* Core metrics */}
        <div className="grid grid-cols-2 gap-x-3 gap-y-1 text-xs">
          <div className="text-gray-400 flex items-center gap-1">
            CAC <span className="text-gray-800 font-medium">
              {d.cac > 0 ? fmt(d.cac, creative.currency) : '—'}
            </span>
            {cacTrendPct !== null && (
              <span className={`${cacTrendPct < 0 ? 'text-green-600' : 'text-red-500'} font-medium`}>
                {cacTrendPct < 0 ? '↓' : '↑'}{Math.abs(cacTrendPct).toFixed(0)}%
              </span>
            )}
          </div>
          <div className="text-gray-400">
            ROAS <span className="text-gray-800 font-medium">
              {d.roas > 0 ? fmtRoas(d.roas) : '—'}
            </span>
          </div>
          <div className="text-gray-400">
            Spend <span className="text-gray-800 font-medium">{fmt(d.spend, creative.currency)}</span>
          </div>
          <div className="text-gray-400">
            Orders <span className="text-gray-800 font-medium">
              {d.purchases > 0 ? d.purchases.toLocaleString() : '—'}
            </span>
          </div>
        </div>

        {/* CTR + Frequency row (Facebook only) */}
        {hasCtrData && (
          <div className="grid grid-cols-2 gap-x-3 text-xs border-t border-gray-100 pt-1.5">
            <div className="text-gray-400">
              CTR <span className="text-gray-800 font-medium">{d.ctr.toFixed(1)}%</span>
            </div>
            <div className="text-gray-400">
              Freq <span className="text-gray-800 font-medium">{d.frequency.toFixed(1)}×</span>
            </div>
          </div>
        )}

        {/* Badges row */}
        <div className="flex flex-wrap gap-1">
          <span className={`badge ${style.bg} ${style.text} text-xs`}>{style.label}</span>
          {isFatiguing && (
            <span className="badge bg-orange-100 text-orange-700 text-xs">Fatiguing</span>
          )}
        </div>

        {/* 4-day switcher */}
        <div className="flex gap-1 mt-auto pt-1">
          {days.map((_, i) => (
            <button
              key={i}
              onClick={() => setActiveDay(i)}
              className={`day-btn text-xs ${activeDay === i ? 'active' : ''}`}
            >
              {i === 0 ? 'Today' : i === 1 ? 'Yday' : `-${i}d`}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}
